name: Issues example

on:
  issues:
    types: [opened]

jobs:
    procesa-issue:
      runs-on: ubuntu-latest
      steps:
        - name: Muestar el título del issue
          run: echo "El titulo del issue es ${{ github.event.issue.title }} "
        
