name: hola mundo

on: 
  workflow_dispatch: 
  # schedule:
  # - cron: "*/5 * * * *"
  #push:
  #  branches:
  #   - main

jobs: 
  saludar:
    runs-on: ubuntu-latest
    steps:
        - name: Muestra mensaje Hola mundo
          run: echo "Hola mundo"
        
