name: hola mundo

on: 
  workflow_dispatch: 
  # schedule:
  # - cron: "*/5 * * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  saludar:
    runs-on: ubuntu-latest
    steps:
        - name: Muestra mensaje Hola mundo
          run: echo "Hola mundo"
        - name: Checkout
          uses: actions/checkout@v4.2.2
        - name: Listar los archvios del repositorio
          run: |
            echo "El repositorio $ {{github.repository}} contiene los archivos:"
            tree
          
        
