name: variables

on:
  workflow_dispatch:

env:
  variable_global: VARIABLE GLOBAL

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      variable_job: VARIABLE JOB
    steps:
      - name: step 1 del job-1
        run: |
          echo el valor de la variable es $variable_global
          echo 'otro forma ${{ env.variable_global }}'
          echo 'otro forma ${{ env.variable_job }}'
          echo 'otro forma ${{ env.variable_step }}'
        env:
          variable_step: VARIABLE STEP

      - name: step 1 del job-1
        run: |
          echo el valor de la variable es $variable_global        
          echo 'otro forma ${{ env.variable_job }}'
  job-2:
    runs-on: ubuntu-latest   
    steps:
     - name: step 1 del job-2
       run: |
          echo el valor de la variable es $variable_global
